### ISSUE TITLE
Translate to Brazilian Portuguese

### ISSUE THREAD

**Issue by ricardovsilva** [ruby/TryRuby#10]
I already started translation to Brazilian Portuguese. I need someone to review that and help with text that are not translated yet.
I did a pull request with text that I already translated, #9

**Comment by easydatawarehousing** [comment]
Hi Ricardo,

Wow, excellent work ! I’ll ask around for help with reviewing translating.

Thanks,
Ivo

From: Ricardo da Verdade Silva 
Sent: Thursday, August 27, 2015 8:58 PM
To: easydatawarehousing/TryRuby 
Subject: [TryRuby] Translate to Brazilian Portuguese (#10)

I already started translation to Brazilian Portuguese. I need someone to review that and help with text that are not translated yet.
I did a pull request with text that I already translated, #9

**Comment by ricardovsilva** [comment]
I talked with a friend of mine, and he will review all translations I already did. If you want see his github profile https://github.com/jhonnymoreira

**Comment by ricardovsilva** [comment]
I think that in more two or three days I end the translation. Can you just look to the first files to see if structure are correct?

**Comment by ricardovsilva** [comment]
Fully translated to Brazilian Portuguese.
I tried to bundle install to test, but I has problems. I opened issue #11 to that.
easydatawarehousing, can you take a look in pull request to see if I broke something?
