### ISSUE TITLE
Site currently displaying output error

### ISSUE THREAD

**Issue by boone** [ruby/TryRuby#103]
Hello, the Output window on try.ruby-lang.org is currently displaying:

```
(file): undefined is not an object (evaluating 't.$$is_string') (Exception)
```

Ruby code does not run. Can that be fixed?

Thanks!

**Comment by boone** [comment]
Oh, interesting, this error only occurs in Safari for me. In Chrome the site is functioning properly.

**Comment by hsbt** [comment]
Thanks for your report. 

I confirmed your issue with Safari 15.1 at macOS 12.0.1. But It didn't appear with Chrome.

**Comment by hmdne** [comment]
I confirm the issue with GNOME Epiphany 41.0 with WebKitGTK 2.34.1. Also it seems like it got fixed by updating Opal to v1.3.1.

**Comment by hsbt** [comment]
@hmdne Thanks a lot!

**Comment by boone** [comment]
@hmdne and @hsbt many thanks!
