### ISSUE TITLE
Chinese version 网站的中文版本

### ISSUE THREAD

**Issue by ye-junzhe** [ruby/TryRuby#112]
Hello, I've been learning Ruby recently and love this site, plus I'm from China, so I'd like to add a Chinese version to this site and I'll try to finish it in a few weeks.

**Comment by ye-junzhe** [comment]
I have a problem with the language drop-down menu in the upper right corner of the page, I don't know which file to modify to add the "Chinese" option. I checked the PR #35 of other translators and found that their <index.html.markdown> is different from the current version. Can someone tell me how to fix it?

**Comment by ye-junzhe** [comment]
Oh!! I think I found it in #107 

Now must modify [_navbar.html.erb ](https://github.com/ruby/TryRuby/blob/master/source/layouts/_navbar.html.erb) to add options

**Comment by hmdne** [comment]
You closed #113 - I assume you want to do further work. Feel free to push a new PR when you are ready for a review :)

**Comment by McF4r** [comment]
> 
#113 was an accident 🤣
#114 check this out

**Comment by ye-junzhe** [comment]
> You closed #113 - I assume you want to do further work. Feel free to push a new PR when you are ready for a review :)

#113 was an accident 🤣
#114 check this out

**Comment by hmdne** [comment]
Great job :D Unfortunately I don't know Chinese so I can't proofread the strings (but I will ask if someone can), on code-side I found no apparent issues.

One tiny issue though, I believe you added a `.DS_Store` file by mistake. It contains some macOS metadata we don't need to store in the repo. It would be great if you could remove it.

**Comment by ye-junzhe** [comment]
> Great job :D Unfortunately I don't know Chinese so I can't proofread the strings (but I will ask if someone can), on code-side I found no apparent issues.
> 
> One tiny issue though, I believe you added a `.DS_Store` file by mistake. It contains some macOS metadata we don't need to store in the repo. It would be great if you could remove it.

I think it is very important to listen to the opinions of others, can’t guarantee that the translation is 100% correct. 🔍 
And .DS_Store is deleted

**Comment by hmdne** [comment]
The Chinese translation has been merged and is live now!

**Comment by ye-junzhe** [comment]
> The Chinese translation has been merged and is live now!

Great work, thanks for your efforts. 🎉
