### ISSUE TITLE
Typo on `Using the editor`

### ISSUE THREAD

**Issue by rodber** [ruby/TryRuby#126]
`Using the editor` on narrow viewport:

<img width="598" alt="image" src="https://user-images.githubusercontent.com/20590102/162452270-2250ee0e-295f-4117-8247-dfe898c3b07e.png">

`Using the editor` gets confusing on Desktop as the editor spawn on right:

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/20590102/162451760-7d812e9e-6cdd-4971-a132-430b49cfedf0.png">

I suggest to omit the location of the editor window.

**Comment by ZimbiX** [comment]
I agree. I've submitted two PRs to address inaccurate position descriptions: https://github.com/ruby/TryRuby/pull/160, https://github.com/ruby/TryRuby/pull/161. I only know English - I'm not sure what's to be done about the other translations.
