### ISSUE TITLE
"All together now" wrong code

### ISSUE THREAD

**Issue by RomainLAU** [ruby/TryRuby#128]
The code to write suggests to finish the script with the line `puts count_plays(0)` while it should be `puts count_plays(1591)`

**Comment by easydatawarehousing** [comment]
Thanks for your remark. Actually I did this on purpose so the user has something to do. Maybe the feedback given could have been a little more informative.

**Comment by RomainLAU** [comment]
Oh I see, that makes sense, thanks for the training, my class is grateful for your website, allowing us to discover ruby :+1:
