### ISSUE TITLE
Integer division creates floats instead of integers.

### ISSUE THREAD

**Issue by raxoft** [ruby/TryRuby#134]
I just tried TryRuby (in Firefox 100.0.2 64bit on Linux) and one of the first examples `30 / 4` shows the result `7.5`. This is completely wrong, and it will confuse lot of beginners, because that's complete opposite of how it should work. I guess this has to do with running in browser instead of irb on server, but it really should be fixed, IMO.

**Comment by eregon** [comment]
Same issue as https://github.com/ruby/TryRuby/issues/122

**Comment by hmdne** [comment]
Fixed by #148

**Comment by raxoft** [comment]
Awesome, thanks!
