### ISSUE TITLE
Minimal TryRuby?

### ISSUE THREAD

**Issue by rubyFeedback** [ruby/TryRuby#136]
Could the documentation mention a minimal TryRuby, just so we can
embed irb in some website? I'd love to be able to do so. That way I
can easily add a "live" irb. Right now I am not sure what I have to
change and tweak. Documentation would be great for that.

**Comment by hsbt** [comment]
You can build it with https://github.com/ruby/ruby.wasm/ or https://github.com/opal/opal.
