### ISSUE TITLE
Using class names suffixed with consecutive numbers triggers type error

### ISSUE THREAD

**Issue by varungandhi-src** [ruby/TryRuby#137]
```
class C1
end

class C2 < C1
end
```

This gives me an error:
```
(file): superclass mismatch for class C2 (TypeError)
```

<img width="773" alt="" src="https://user-images.githubusercontent.com/93103176/190538996-294209f6-5b9c-4be4-be57-fc0fbe2c5c43.png">

Renaming the `C2` to `D` fixes the error. I don't know much Ruby, but this seems unexpected... Testing this code locally with 2.7.2 works fine. Is there some internal name modification going on which is creating a class named `C2` which is colliding with the hand-written definition?

**Comment by hsbt** [comment]
@hmdne Can you look this? I think it's issue of Opal.

**Comment by hmdne** [comment]
The problem is that the Opal runner runs in the browser context, so every constant definition persists. A solution for that could be to run Opal in a web worker.

**Comment by hmdne** [comment]
I have added an Opal WebWorker runner in #141, but we need to wait for an Opal 1.7.1 release to switch to it.
