### ISSUE TITLE
 Wrong answer output in "All together now" exercise

### ISSUE THREAD

**Issue by vivid-pixel** [ruby/TryRuby#153]
Couldn't find the error in my typed version of the code, so then I copied the provided solution and discovered it had the same output error:
```
0
Answer for the year 1591 should be 4
```
<img width="1582" alt="try-ruby-exercise" src="https://github.com/ruby/TryRuby/assets/42875253/c134d7d7-21de-43e3-805f-034e10765eb5" alt="screenshot of exact provided code failing to provide correct output answer">

**Comment by hmdne** [comment]
You are expected to change the copied code for this particular example.

See #128
