### ISSUE TITLE
Turkish translation

### ISSUE THREAD

**Issue by arsahindev** [ruby/TryRuby#171]
Hi there! I've just went through the whole TryRuby course and it was a really playful and simple tutorial which introduced me into the fundamentals of the language and thank you for creating such website!
I benefited a lot from this simple website and would love to create a translation for it.

Wanted to create this issue just as a heads up to let you know I'll be working on it and be finished with it in a relatively short amount of time. I've already forked the repository and got to working! :)

Here's the PR that I've opened: https://github.com/ruby/TryRuby/pull/172

**Comment by arsahindev** [comment]
After the merge of [this PR](https://github.com/ruby/TryRuby/pull/174) which includes the things that were previously forgotten, this issue has been resolved.

![Screenshot 2024-04-03 at 12 50 10](https://github.com/ruby/TryRuby/assets/80679047/08eff990-bfec-40fa-9551-ae82d9b812a4)
![Screenshot 2024-04-03 at 12 50 25](https://github.com/ruby/TryRuby/assets/80679047/f7b2fae9-eddd-47c0-94df-5e6b74cf4cb7)

**Comment by arsahindev** [comment]
Done. Now, you can access the Turkish version of TryRuby from the official link! https://try.ruby-lang.org/

**Comment by hsbt** [comment]
Thank you for your work!
