### ISSUE TITLE
NoMethodError error for String#[]=

### ISSUE THREAD

**Issue by razum2um** [ruby/TryRuby#26]
https://ruby-doc.org/core-2.5.1/String.html#method-i-5B-5D-3D
```
say = "I love Ruby"
say['love'] = "*love*"
say
```
expected
```
I *love* Ruby
```
actual
```
NoMethodError: undefined method `[]=' for "I love Ruby"
```
this chunk of code is notably shown on [ruby homepage](https://raw.githubusercontent.com/ruby/www.ruby-lang.org/master/en/examples/i_love_ruby.md)

**Comment by easydatawarehousing** [comment]
Thanks for reporting this issue. But this is something I don't think I can change. TryRuby uses Opal for running Ruby in a web browser. Opal transpiles ruby to javascript. In javascript strings are immutable. Opal copies this behavior, see [undocumented features](http://opalrb.com/docs/guides/v0.11.1/unsupported_features.html).

I am in the process of updating the Opal version used by TryRuby. Using the latest Opal (0.11.4) the string indexing does work.

    say = "I love Ruby"
    say['love']

it returns 'love' as expected.

Starting irb with immutable strings (`RUBYOPT=--enable-frozen-string-literal irb`) and using your example will produce a similar error on the `[]=` method.
