### ISSUE TITLE
Error in "Hungry" section.

### ISSUE THREAD

**Issue by arknamal** [ruby/TryRuby#28]
The Section named "Hungry" is throwing an error at this code. It is running perfectly okay in ruby console and a ruby file on my machine. I think there is some problem there.
def hungry?(time_of_day_in_hours)
  if time_of_day_in_hours < 12
    puts "Me not hungry."
    return false
  end
  puts "Me hungry."
  return true
end

def eat_an(what)
  puts "Me eat #{what}.\n"
end

eat_an 'apple' if hungry?(14)

eat_an 'apple' if hungry?(10)

**Comment by arknamal** [comment]
The indentation was lost when I submitted.

**Comment by easydatawarehousing** [comment]
I have updated a lot of gems including Opal. Works for me now [here](https://easydatawarehousing.github.io/TryRuby/). Still needs to be updated on the fork of this repo that ruby-lang.org uses.

**Comment by easydatawarehousing** [comment]
In production.
