### ISSUE TITLE
Add portuguese translation

### ISSUE THREAD

**Issue by abinoam** [ruby/TryRuby#3]
I've began working on the portuguese translation. I'll make a pull request when it's finished.
I'm opening this issue just to have a place to discuss the translation with anyone that wishes to cooperate on it.

https://github.com/abinoam/TryRuby/tree/pt-translation

Comparing to master: https://github.com/abinoam/TryRuby/compare/pt-translation?expand=1

**Comment by easydatawarehousing** [comment]
Wow. That is great news, thanks.

Just pushed the Dutch translation. Also made some updates to the English version, so you may want to pull these first.
I have updated the translation/readme file with some suggestions. Mainly: I have chosen not to translate the poem and the app content. And for important words like 'hash', I'm using the English word and give a translation the first time that the word is used.

I will update the website soon. After some more reviewing of the Dutch text.

Ivo

**Comment by abinoam** [comment]
Ok. I'll be rebasing after your modifications.
