### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by mhoncharov** [ruby/TryRuby#33]
I think it will be great to have the Russian language. Because there are a lot of Russian-speaking developers.

I am going to create localization for it.

**Comment by easydatawarehousing** [comment]
Great idea! Maybe @startaper is working on this as well.

**Comment by nikolaev-dev** [comment]
Yes, I have almost finished version.

**Comment by nikolaev-dev** [comment]
pull request done 
https://github.com/easydatawarehousing/TryRuby/pull/35
