### ISSUE TITLE
Readme.md: Two 404 links

### ISSUE THREAD

**Issue by duianto** [ruby/TryRuby#37]
Two links in Readme.md leads to a page that says:
>404
There isn't a GitHub Pages site here.

### 1 

In the section: https://github.com/ruby/TryRuby#publishing
the link text: easydatawarehousing.github.io/TryRuby/
leads to: https://easydatawarehousing.github.io/TryRuby/

### 2 

In the section: https://github.com/ruby/TryRuby#why
the link text: try-ruby-version-4
leads to: https://easydatawarehousing.github.io/TryRuby/articles/try-ruby-version-4/

**Comment by easydatawarehousing** [comment]
Thanks. I will take a look at this this weekend. We moved from 'easydatawarehousing' to 'ruby' yesterday. Needs a bit of cleanup.

**Comment by easydatawarehousing** [comment]
Fixed. Together with some other dead(ish) links.
