### ISSUE TITLE
Ringlets of Chained Methods: Successful response, missing a line break

### ISSUE THREAD

**Issue by duianto** [ruby/TryRuby#39]
On the page: https://ruby.github.io/TryRuby/

In the exercise: Ringlets of Chained Methods

The response when successfully running the code, says:
>Good show, my friend! The join method took that array of lines and put them together into a string.

The string probably needs a line break, because it spans outside the right edge of the output window:

![chrome_2019-02-08_15-04-09](https://user-images.githubusercontent.com/13420573/52482954-eb197d00-2bb2-11e9-829b-e9c8f3620ce6.png)

This causes a horizontal scrollbar to appear.

It would be better if the successful response had a line break, so that it could be read without having to scroll horizontally.

**Comment by duianto** [comment]
The same issue occurs with the error message in the exercise: `A Wee Blank Book`

![image](https://user-images.githubusercontent.com/13420573/52489294-2f604980-2bc2-11e9-982d-fcf9d6b68a6d.png)

**Comment by easydatawarehousing** [comment]
Fixed.

**Comment by duianto** [comment]
One slight issue, the line height might need to be increased.

In the `Ringlets of Chained Methods` lesson.

The background of the second line covers the bottom of the `,` (comma) after "show" and `y` in "my" on the first line.

![chrome_2019-02-11_08-19-50](https://user-images.githubusercontent.com/13420573/52549994-555e3780-2dd6-11e9-9338-a7537edea365.png)

For demonstration (not a suggestion for a fix), adding `margin-top: 4px` the pre tag shows them without overlap: 
```html
<pre style="margin-top: 4px;">
  <span style="padding-right: 0.1px;">
    <span class=" tryruby-output-green">The join method took that array of lines and put them together into a string.</span></span></pre>
```
![chrome_2019-02-11_08-21-18](https://user-images.githubusercontent.com/13420573/52550118-0533a500-2dd7-11e9-9cf9-0bd7c0c6a178.png)

The same thing happens with the `p` and `,` in the `A Wee Blank Book` lesson:

![chrome_2019-02-11_08-30-03](https://user-images.githubusercontent.com/13420573/52550208-52177b80-2dd7-11e9-8468-8bd1a5af5f77.png)
