### ISSUE TITLE
Using ctime is not working on mac

### ISSUE THREAD

**Issue by abinoam** [ruby/TryRuby#4]
ctime is not catching file content changing on a mac os x 10.9.4 with ruby 2.1.5 (rvm) and sublime text.
(I didn't investigated any futher... but...)
mtime catches the file content changes correctly. So, changed to mtime on 68038e3bd6a6. PR soon.

**Comment by easydatawarehousing** [comment]
Ah yes, that is better. A hint in Ruby-doc about the difference between ctime and mtime would have been nice ;-)
Thanks, PR is merged.
Ivo

**Comment by abinoam** [comment]
They say ctime is "more" than mtime. So, every situation mtime alters, ctime should alter too. 
But, I don't know why, it is not working on my setup (and probably at other person's too).
