### ISSUE TITLE
Couple of typos

### ISSUE THREAD

**Issue by marklocklear** [ruby/TryRuby#53]
Typo in the first paragraph "So far we have been running programs that only use things that we have typed ourselves. Which is nice, I mean that Odelaying was epic, but this **is** the internet era so it is about time we included the rest of the world in our programming efforts." The "is" is missing.

Typo in "Summary #6" under "Data" instead of "You loaded some data of the internet..." it should read "You loaded some data off the internet..."

**Comment by stomar** [comment]
The first typo was already fixed with #57.

**Comment by stomar** [comment]
Thanks for pointing this out!
