### ISSUE TITLE
Try Ruby - Are You Harsh error

### ISSUE THREAD

**Issue by AnestisK** [ruby/TryRuby#66]
I am up to the "Are You Harsh" Lesson, and when I enter (or copy)

```
books.values.each { |rate|
  ratings[rate] += 1
}

```
and press Run, I get the error message "ratings: undefined method `ratings' for main"
![image](https://user-images.githubusercontent.com/13781656/74304159-4080ff00-4db0-11ea-91f7-57b0636573d6.png)

**Comment by easydatawarehousing** [comment]
That is because ratings is not defined. If you write `ratings = Hash.new {0}` above the current lines (or use the copy button) it should work as expected.

**Comment by AnestisK** [comment]
Hmm OK.
Tutorial doesn't make it clear that you have to copy everything into the Editor to make it work.  Was trying to do it statement by statement like in CodeCademy (as in the first line, then the second statement (block), then the third line.
