### ISSUE TITLE
Revive Spanish translation

### ISSUE THREAD

**Issue by easydatawarehousing** [ruby/TryRuby#7]
TryRuby release 2 used to have a Spanish translation of the lesson content. This can be found in the translations/converted subdir.

Discussion on how to revive this translation are welcome.

Ivo

**Comment by jgabrielygalan** [comment]
What's your opinion on translating technical words such as: array, string, etc? Here in Spain, even when speaking in Spanish, we tend to use those words as they are in English. It's been a long time since I read anything technical in Spanish, I mostly read English documentation, so I'm not sure about what's best.

**Comment by easydatawarehousing** [comment]
Good point. It is the same here, everything is written in English, like: variable names, comments, tests. Everything except cucumber features.

But I think we should keep in mind for whom we are writing these translations. The main 'user profile' I have in mind is someone in the age range 12 - 25 years old who is just starting to learn programming. And may not have a good understanding of English yet.

In the translations/README.md file I have given some suggestions:

> Some TryRuby things are difficult to translate. For instance the toast poem.
> For the Dutch translation I have chosen not to translate this.
> 
> Since Ruby itself is English it is inevitable that some of the lesson content contains English words.
> For the Dutch translation I've left in all important English words (like hash) and gave a translation
> or description the first time such a word is encountered.
> 
> You probably should not translate Blurb and Blurbalizer. I've also left the Blurb content
> untranslated.

I should add to this that I have translated variable names (like ticket) into something more understandable. And added a comment about English being the programmers 'native' language on the 'toast poetry' page.

**Comment by jgabrielygalan** [comment]
Do we have to push the source/try_ruby_es.json generated file?

**Comment by easydatawarehousing** [comment]
That would be nice. I can do it for you if you like. Sending a separate email about the PR.

**Comment by jgabrielygalan** [comment]
I'll commit the try_ruby_es.json to the pull request
