### ISSUE TITLE
Deploy master on production

### ISSUE THREAD

**Issue by aleksandrilyin** [ruby/TryRuby#72]
Update site.

**Comment by hsbt** [comment]
@easydatawarehousing I added auto-deploy configuration used GitHub Actions.

see https://github.com/ruby/TryRuby/blob/master/.github/workflows/deploy.yml

When we pushed master branch, It was triggered.

**Comment by aleksandrilyin** [comment]
Thank you!

**Comment by easydatawarehousing** [comment]
Cool !
Github actions is a very nice feature. Inspired by Bitbucket pipelines ;)
