### ISSUE TITLE
Text formatting, example code, and copy function

### ISSUE THREAD

**Issue by a-olsen** [ruby/TryRuby#99]
Text does not appear to be formatted correctly.

Example code box is missing.

Copy function is broken most likely because the example box is missing.

**Comment by a-olsen** [comment]
The page loads correctly for a split second.  Then it loses the formatting and example functionality.

Could a script that runs after the page is brought up be breaking it?

**Comment by hmdne** [comment]
This was due to an upgrade I made with #98, I made a mistake of not copying a Markdown call. I will just test this upgrade and make a pull request.

**Comment by a-olsen** [comment]
Awesome, thank you so much.  I am a college instructor and I use this in an introduction to computers class to put in to practice the terms we learned about programming.  I love this project and it really helps students to understand what is going on behind the scenes and it keeps them involved with the humor and fun it provides.

**Comment by hmdne** [comment]
That's great to hear! Ruby is certainly a fun environment which must mean your students have a lot of fun :D. I also launched another pull request #101 which should make your job a little bit easier.
